[package]
name = "console"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "0.16.0"
async-std = { version = "1.10.0", features = ["attributes"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
